%% gyroChar_instr_NA_initFreqResponse
function deviceObj = gyroChar_instr_NA_initFreqResponse(deviceObj, varargin)
%% gyroChar_instr_NA_initFreqResponse


%% Initialize measurement of magnitude
invoke(deviceObj.Channelmeasurement,...
       'channelmeasurementcreate', 'Channel1:Measurement1',0,0);
invoke(deviceObj.Attributeaccessors(1), 'setattributeviint32',...
       'Channel1:Measurement1',...
       deviceObj.UserData.AGNA_ATTR_CHANNEL_MEASUREMENT_FORMAT,...
       deviceObj.UserData.AGNA_VAL_AGILENT_NA_MEASUREMENT_LOG_MAG);
   
%% Initialize measurement of phase
invoke(deviceObj.Channelmeasurement,...
    'channelmeasurementcreate', 'Channel1:Measurement2',0,0);
invoke(deviceObj.Attributeaccessors(1), 'setattributeviint32',...
       'Channel1:Measurement2',...
       deviceObj.UserData.AGNA_ATTR_CHANNEL_MEASUREMENT_FORMAT,...
       deviceObj.UserData.AGNA_VAL_AGILENT_NA_MEASUREMENT_PHASE);